name: BuildHouse
version: 1.0
main: at.htl.mccoding.buildHouse.Main
description: Builds Houses
api-version: 1.13
commands:
  build:
    description: builds houses
  destroy:
    description: destroys houses
  listHouses:
    description: lists houses
  fillHouse:
    description: fills houses with TNT